name: medication_reminder
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^4.1.1
  video_player: ^2.9.2

flutter:
  uses-material-design: true
