// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-0_20vj8b-eauHwy0FOqO41dXs6qWTNA',
    appId: '1:815991442031:web:9dfd52776020bf0e589b9a',
    messagingSenderId: '815991442031',
    projectId: 'test-fd40d',
    authDomain: 'test-fd40d.firebaseapp.com',
    storageBucket: 'test-fd40d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01gwyCG8ArPXfqjkd_EPBjqzOwSM_SzY',
    appId: '1:815991442031:android:8c4806b3577fe158589b9a',
    messagingSenderId: '815991442031',
    projectId: 'test-fd40d',
    storageBucket: 'test-fd40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZW9pKSkAVI_Qwy8I2YL-6X7LZBHPryVs',
    appId: '1:815991442031:ios:e4aba61549c7b64b589b9a',
    messagingSenderId: '815991442031',
    projectId: 'test-fd40d',
    storageBucket: 'test-fd40d.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZW9pKSkAVI_Qwy8I2YL-6X7LZBHPryVs',
    appId: '1:815991442031:ios:e4aba61549c7b64b589b9a',
    messagingSenderId: '815991442031',
    projectId: 'test-fd40d',
    storageBucket: 'test-fd40d.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-0_20vj8b-eauHwy0FOqO41dXs6qWTNA',
    appId: '1:815991442031:web:9f876bbed131cf4c589b9a',
    messagingSenderId: '815991442031',
    projectId: 'test-fd40d',
    authDomain: 'test-fd40d.firebaseapp.com',
    storageBucket: 'test-fd40d.firebasestorage.app',
  );

}